CREATE SCHEMA killedby;

CREATE TYPE gender AS ENUM ( 'Male', 'Female' );

CREATE TYPE cause AS ENUM (
	'Drone',
	'Gun',
	'Restraint/Physical Force',
	'Taser',
	'Vehicle',
 	'Chemical',
	'Other'
);

CREATE TABLE event_class (
	event_class_id    int    PRIMARY KEY
		GENERATED BY DEFAULT AS IDENTITY,
	event_class_name  text   UNIQUE,
	event_class_desc  text
);

--
-- I really wanted Zionism, but if the site takes off
-- that category will be problematic, because it's just
-- occupation.
--
INSERT INTO event_class(event_class_name, event_class_desc) VALUES
	('Police',     'Domestic cost of maintaining the state'),
	('Invasion',   'One state temporarily attacks another'),
	('Occupation', 'State denies sovereignty or citizenship');

CREATE TABLE source_class (
	source_class_id     int  PRIMARY KEY
		GENERATED BY DEFAULT AS IDENTITY,
	source_class_name   text UNIQUE,
	source_class_desc   text
);

INSERT INTO source_class (source_class_name, source_class_desc) VALUES
	( 'News'        , $$Information about the event$$ ),
	( 'Judicial'    , $$State's response (investigation, trial, etc)$$ ),
	( 'Response'    , $$Community's response (riot, protest, demonstration)$$ );

CREATE TABLE events (
	event_id    int PRIMARY KEY
		GENERATED BY DEFAULT AS IDENTITY,
	event_class_id int REFERENCES event_class,
	
	event_date  date,

	state       char(2),
	city        text,
	geog        public.geography(POINT,4326),
	
	cause       cause,
	is_direct   bool
	
	--user_added        int REFERENCES user,
	--user_modified     int REFERENCES user,
);


CREATE TABLE sources (
	source_id         int  PRIMARY KEY
		GENERATED BY DEFAULT AS IDENTITY,
	event_id          int  REFERENCES events,
	
	source_class_id   int  REFERENCES source_class,
	title             text,
	
	source_url        text,

	date_authored     date,
	date_submitted    date DEFAULT CURRENT_DATE
	
	--user_added        int REFERENCES user,
	--user_modified     int REFERENCES user,
);

CREATE TABLE killer (
	killer_id        int PRIMARY KEY
		GENERATED BY DEFAULT AS IDENTITY,

	event_id         int REFERENCES events,
	killer_org_id    text, -- badge number
	name_given       text,
	name_surname     text,
	agency_oir       char(9) REFERENCES fbi.agencies	
	
	--user_added        int REFERENCES user,
	--user_modified     int REFERENCES user,
);

CREATE TABLE victims (
	victim_id        int    PRIMARY KEY
		GENERATED BY DEFAULT AS IDENTITY,

	event_id         int    REFERENCES events,
	name_given       text,
	name_surname     text,
	date_birth       date,
	date_death       date,
	race             census.race,
	ethnicity        census.ethnicity,
	gender           gender,
	is_trans         bool,
	is_immigrant     bool,
	is_incarcerated  bool,
	death_date       date
	
	--user_added        int REFERENCES user,
	--user_modified     int REFERENCES user,
);
